### ISSUE TITLE
CRAN availability

### ISSUE THREAD

**Issue by alexvolkmann** [ClaraHapp/funData#20]
Hey Clara,

FYI:

"Package ‘funData’ was removed from the CRAN repository. [..] Archived on 2021-07-27 as maintainer's address does not comply with CRAN policy. [...]"

Same with MFPCA package. Are you planning on re-uploading to CRAN?

Best,
Alex

**Comment by ClaraHapp** [comment]
Hi Alex,

thanks a lot for letting me know. I will try to get the packages back on CRAN. In the meantime, you can install them via `devtools::install_github()`.

Best,
Clara

**Comment by alexvolkmann** [comment]
Hey Clara,

perfect, thanks! I was asking because I wanted to upload my own package on CRAN and it imports both of these packages :+1: 

Best,
Alex

**Comment by fabian-s** [comment]
hi @ClaraHapp  --- could you let me know once they're back on CRAN? 
I had to remove your packages from the FDA task view for the time being and would like to add them back as soon as possible.

**Comment by ClaraHapp** [comment]
@alexvolkmann @fabian-s `funData` is back on CRAN: https://cran.r-project.org/web/packages/funData/index.html
`MFPCA` was submitted today and should follow soon. I will keep you posted.

**Comment by ClaraHapp** [comment]
@alexvolkmann @fabian-s `MFPCA` is finally back on CRAN: https://cran.r-project.org/web/packages/MFPCA/index.html
The functionality is unchanged, I had to fix a test that was failing in MKL, change email address (to something without auto-reply) and adapt the documentation a bit to pass the CRAN tests again.
Thanks a lot for your patience and looking forward to see your package on CRAN, @alexvolkmann :)

**Comment by fabian-s** [comment]
Super, @ClaraHapp! I'll update the FDA task view ;)
